require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
pod 'ffmpeg-kit-react-native', :subspecs => ['full-gpl'], :podspec => '../node_modules/ffmpeg-kit-react-native/ffmpeg-kit-react-native.podspec'

platform :ios, '12.1'

target 'Athes_MobileApp' do
   
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )


   permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'react-native-background-actions', :path => '../node_modules/react-native-background-actions'
  
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-fast-video', :path => '../node_modules/react-native-fast-video'
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary" 
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"

  target 'Athes_MobileAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()

  

  post_install do |installer|
  # installer.pods_project.targets.each do |target|
  #   target.build_configurations.each do |config|
  #     if Gem::Version.new('8.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
  #       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
  #     end
  #   end
  # end
  installer.pods_project.targets.each do |target|
    if target.name == "React-Core-AccessibilityResources"
      target.remove_from_project
    end
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
end

